#!/usr/bin/perl -w

#use lib "/home/pi/media/scripts/perl/";
use lib "/opt/fpp/plugins/ProjectorControl/";

use ProjectorControl;


my $input = $ARGV[0] || "";

my $line1 = "";
my $line2 = "";


$line1 = $ARGV[0] if (defined($ARGV[0]));
$line2 = $ARGV[1] if (defined($ARGV[1]));


my $projector = new ProjectorControl("$line2");

my $str = $line1;

$projector->print($str);

