#!/usr/bin/perl -w

#use lib "/home/pi/media/scripts/perl/";
use lib "/opt/fpp/plugins/ProjectorControl/";

use ProjectorControl;

use IO::Socket::INET;

my $input = $ARGV[0] || "";



my $line1 = "";
my $line2 = "";
my $line3 = "";


#text is line 2

$line1 = $ARGV[0] if (defined($ARGV[0]));
$line2 = $ARGV[1] if (defined($ARGV[1]));
$line3 = $ARGV[2] if (defined($ARGV[2]));



my $projector = new ProjectorControl($line1);



# flush after every write
$| = 1;
my ($socket,$data);



#  We call IO::Socket::INET->new() to create the UDP Socket 
# and bind with the PeerAddr.



$socket = new IO::Socket::INET (
PeerAddr   => "$line2",
Proto        => 'tcp',
Type => SOCK_STREAM
) or die;
#send operation


# write on the socket to server.
$data = $projector->createString($str);

#printf($data);


# we can also send the data through IO::Socket::INET module,
$socket->send($data);
	
$socket->close();